namespace HdUtilities.Enum
{
    public enum FileTypeEnum
    {
        Picture,
        Movie,
        Gif,
        Pdf,
        Zip,
        Text,
        RealPlayer,
        Audio,
        WebHtml,
        FileSystemReference,
        Other,
        ChromeDownload,
        Batch,
        CommaDelimited,
        MsExcel,
        MsWord,
        Executable,
        Java,
        CSharp,
        CPlusPlus,
        SQLiteDatabase,
        Json,
        Xml
    }
}